import { Container } from "react-bootstrap";
import "./Planner.css";

const Planner = ({plan=[]}) => {

    const stepIcons = [
    "bx-bulb",
    "bx-world",
    "bx-book-open",
    "bx-git-compare",
    "bx-file"
];

   const getStepTitle = (step) => {
    if (typeof step === "string") {
        return step.replace(/^#+\s*/, "").replace(/^Step\s+\d+\s*:\s*/i, "").trim();
    }

    if (typeof step === "object" && step !== null) {
        return (
            step.title ||
            step.step ||
            step.description ||
            ""
        );
    }

    return "";
};

    return (
        <section className="planner-section" id="planner">

            <Container>

                {/* Section Header */}

                <div className="planner-header">

                    <span className="planner-badge">
                        <i className="bx bx-brain"></i>
                        AI Research Planner
                    </span>

                    <h2 className="planner-title">
                        Your Research
                        <span> Plan</span>
                    </h2>

                    <p className="planner-description">
                        AI breaks your research topic into focused steps
                        before gathering and analyzing information.
                    </p>

                </div>


                {/* Planner Card */}

                <div className="planner-card">

                    {/* Card Header */}

                    <div className="planner-card-header">

                        <div className="planner-card-icon">
                            <i className="bx bx-task"></i>
                        </div>

                        <div>

                            <h3>
                                Research Strategy
                            </h3>

                            <p>
                                AI-generated research workflow
                            </p>

                        </div>

                        <span className="planner-status">

                            <span className="status-dot"></span>

                            Ready

                        </span>

                    </div>


                    {/* Research Steps */}

                    <div className="planner-steps">

                        {plan?.map((step, index) => (

                            <div
                                className="planner-step"
                                key={index}
                            >

                                {/* Step Number */}

                                <div className="step-number">
                                    {String(index+1).padStart(2, "0")}
                                </div>


                                {/* Connector */}

                                {index !== plan.length - 1 && (
                                    <div className="step-connector"></div>
                                )}


                                {/* Step Content */}

                                <div className="step-icon">

                                    <i className={`bx ${stepIcons[index]||"bc-task"}`}></i>

                                </div>

                                <div className="step-content">

                                    <h4>
                                          {getStepTitle(step)}
                                    </h4>

                                    <p>
                                      Research workflow step generated by the AI research agent
                                    </p>

                                </div>

                                {/* Completed Indicator */}

                                <div className="step-check">

                                    <i className="bx bx-check"></i>

                                </div>

                            </div>

                        ))}

                    </div>


                    {/* Planner Footer */}

                    <div className="planner-footer">

                        <div className="planner-info">

                            <i className="bx bx-info-circle"></i>

                            <span>
                                The plan will be executed by the AI research agents.
                            </span>

                        </div>

                        

                    </div>

                </div>

            </Container>

        </section>
    );
};

export default Planner;