from typing import Optional
from pydantic import BaseModel, Field 


class Requestschema(BaseModel):
     """Request received from the frontend."""
     query : str = Field(..., description = "Research topic entered by user") 


class Planner_response(BaseModel):
      """planner Agent output"""
      plan :list[str]= Field(..., description = "Research plan generated by planner agent")



class Toolresponse(BaseModel):
     """Information collected from external tools."""
     web_result: Optional[str] = Field(
        default=None,
        description="Information collected from Web Search."
    )

     wikipedia_result: Optional[str] = Field(
        default=None,
        description="Information collected from Wikipedia."
    )

     arxiv_result: Optional[list[dict]] = Field(
        default=None,
        description="Research papers collected from Arxiv."
    )


class Researchresponse(BaseModel):
       """Complete response returned to the frontend."""

       status: str = Field(..., description = "request status")

       query: str = Field(..., description = "Original user query")

       planner : Planner_response

       tools : Toolresponse

       final_report :str = Field(..., description="Professional research report generated by report writter agent.")
       
       final_report_with_citation:str = Field(..., description = "Final report with in-text citations and references generated by citation agent.")


       
class Documentrequest(BaseModel):
      """Request recieved for DOCX generation"""

      final_report_with_citation : str = Field(..., description = "Final research report with citations to be converted into DOCX format.")
