from pydantic import BaseModel, Field
from model.model import llm
from  states.research_state import ResearchState
from typing import  Optional

class FactCheckerOutput(BaseModel):

    """structured out generated by the fact checker agent. It contains the verified information."""

    verified_information : list[str] = Field(
                                 description = """A detailed verified knowledge document.
                                It should preserve all useful information after removing only
                                duplicates and incorrect facts.""" 
                                 )



fact_checker_model  = llm.with_structured_output(FactCheckerOutput)

def fact_checker_agent(state :ResearchState) -> dict:
    """
    Validates and consolidates information collected from
    Web Search, Arxiv and Wikipedia
    Also remove redundant information
    """
    prompt = f"""

        You are an expert AI Research Fact Checker.

        You are given information collected from multiple trusted sources.

        User Query:
        {state["query"]}


        Web Search Result:
        {state["web_result"]}


        Arxiv Research Papers:
        {state["arxiv_result"]}


        Wikipedia Result:
        {state["wikipedia_result"]}


        Instructions:

        1. Verify all information.

        2. Remove duplicated information.

        3. Resolve conflicting information.
        - Prefer Arxiv over Web Search.
        - Prefer Web Search over Wikipedia for latest facts.
        - Use Wikipedia only for background knowledge.

        4. Never hallucinate.

        5. Do not invent any new information.

        6.  Preserve all useful technical details, explanations, examples, statistics, and research findings

        7. Merge information from all sources into one coherent knowledge document.

        8. Do NOT summarize the information.
        
        9. Do NOT unnecessarily shorten the content.

        10. Organize the information into logical paragraphs.

        11. Keep the maximum amount of verified information possible.

        12. Produce a detailed verified knowledge base that another AI agent can use to generate a comprehensive research report.
    Return only structured output"""
    
    result = fact_checker_model.invoke(prompt)
    return {"verified_information": result.verified_information}
