from pydantic import BaseModel, Field
from model.model import llm
from states.research_state import ResearchState
from typing import  Optional

class KnowledgeSynthesizerOutput(BaseModel):
    """ structured output generated by the knowledge synthesizer agent. It contains the synthesized knowledge from the verified information.

    """
    introduction: str = Field(..., description="Introduction to the topic")

    background: str = Field(..., description="backgroud of the topic")

    core_concepts: str = Field(..., description="core concepts of the topic")

    working_principle: str= Field( ..., description="working principle of the topic")

    architecture: str = Field(..., description="architecture of the topic")

    recent_research: str = Field(..., description="recent research on the topic")

    applications: str = Field(..., description="applications of the topic")

    advantages: str = Field(..., description="advantages of the topic")

    limitations: str = Field(..., description="limitations of the topic")

    future_scope: str = Field(..., description="future scope of the topic")

    conclusion: str = Field(..., description="conclusion of the topic")

    source: list[str] = Field(..., description="sources of the information used in the knowledge document")

    mathematical_foundation: Optional[str] = Field(None, description="mathematical formulation of the topic")

    implementation: Optional[str] = Field(None, description="implementation details of the topic")

    additional_sections: Optional[str] = Field(None, description="Any additional topic-specific sections that do not fit into the predefined categories")


knowledge_synthesizer_model = llm.with_structured_output(KnowledgeSynthesizerOutput)

def knowledge_synthesizer_agent(state: ResearchState) -> dict:
    """
    Organizes the verified information into a structured knowledge base
    which will be used by the Report Generator Agent.
    """

    prompt  = f""" You are an expert AI Knowledge Synthesizer.

You are given verified research information that has already been fact-checked.

Your responsibility is NOT to verify facts again.

Your responsibility is to organize the information into a professional,
well-structured knowledge document.

User Query:
{state["query"]}

Verified Information:
{state["verified_information"]}

Instructions:

1. Do NOT remove useful information.

2. Preserve every important technical detail.

3. Do NOT hallucinate.

4. Do NOT invent any information.

5. Merge related concepts together.

6. Organize the knowledge into logical sections.

7. Maintain a smooth flow between sections.

8. Explain concepts wherever necessary.

9. Keep research findings together.

10. Keep applications together.

11. Keep limitations together.

12. Keep future scope together.

13. Produce a detailed knowledge document suitable for generating
a comprehensive research report.

14. Do NOT write the final report.

15. Return only structured output."""
    
    result = knowledge_synthesizer_model.invoke(prompt)
    return {
    "introduction": result.introduction,
    "background": result.background,
    "core_concepts": result.core_concepts,
    "working_principle": result.working_principle,
    "architecture": result.architecture,
    "recent_research": result.recent_research,
    "applications": result.applications,
    "advantages": result.advantages,
    "limitations": result.limitations,
    "future_scope": result.future_scope,
    "conclusion": result.conclusion,
    "source": result.source,
    "mathematical_foundation": result.mathematical_foundation,
    "implementation": result.implementation,
    "additional_sections": result.additional_sections
        }