from states.research_state import ResearchState
from model.model import llm
from pydantic import BaseModel,Field
from typing import Optional

class PlannerOutput(BaseModel):
    """Structured output of every step generated by planner agent"""


    plan :list[str] = Field(description = "step by step research plan")

    use_web_tool : bool = Field(description = "whether to web search tool is required or not")
    use_arxiv_tool : bool = Field(description = "whether to arxiv tool for research paper is required or not")
    use_wikipedia_tool : bool = Field(description = "whether to wikipedia search tool is required or not")

    web_query: Optional[str]=Field(description = "Optimised query for web search tool")
    arxiv_query: Optional[str]=Field(description = "Optimised query for arxiv tool")
    wikipedia_query: Optional[str]=Field(description = "Optimised query for wikipedia search tool")



planner_llm = llm.with_structured_output(PlannerOutput)

def planner_agent(state:ResearchState) -> ResearchState:
    query = state['query']
    prompt = f"""
You are an expert research planning agent.

Your task is to analyze the user's research query
and decide the best research strategy.

Available tools:

1. Web Search Tool
   - Used for latest information, news, current events.

2. Arxiv Tool
   - Used for research papers and scientific information.

3. Wikipedia Tool
   - Used for general background knowledge and concepts.


   User Query:
    {query}

    Rules:

- Select only required tools.
- Do not select unnecessary tools.
- Create optimized search queries for selected tools.
- Create a clear step-by-step research plan.
- Return structured output only.
- if there is any kind of glitch just don't halucinate.
- give only accurate result.
"""
    result = planner_llm.invoke(prompt)
    return{
            "query": query,
            "plan": result.plan,
            "use_web_tool": result.use_web_tool,
            "use_arxiv_tool": result.use_arxiv_tool,
            "use_wikipedia_tool": result.use_wikipedia_tool,

            "web_query": result.web_query,
            "arxiv_query": result.arxiv_query,
            "wikipedia_query": result.wikipedia_query


    }

